SYMMETRY_BREAKING = 0
NO_SYMMETRY_BREAKING = 1
# SYM_DICT = {SYMMETRY_BREAKING: "_sb", NO_SYMMETRY_BREAKING: ""}
SYM_DICT = {NO_SYMMETRY_BREAKING: ""}

# CP

# SAT
LINEAR_SEARCH = 0
BINARY_SEARCH = 1
# STRATEGIES_DICT = {LINEAR_SEARCH: "linear", BINARY_SEARCH: "binary"}
# STRATEGIES_DICT = {LINEAR_SEARCH: "linear"}
STRATEGIES_DICT = {BINARY_SEARCH: "binary"}

# SMT

# MIP