SYMMETRY_BREAKING = 0
NO_SYMMETRY_BREAKING = 1
SYM_DICT = { NO_SYMMETRY_BREAKING: "", SYMMETRY_BREAKING: "_symbreak"}
##SYM_DICT = {NO_SYMMETRY_BREAKING: "",}

# CP
CHUFFED = 0
GECODE = 1
HIGHS = 2
LCG = 3
GECODE_HEU = 4
SOLVERS_CP = {CHUFFED:'chuffed', GECODE:'gecode',GECODE_HEU: "gecode_heu"}


# SAT & SMT
LINEAR_SEARCH = 0
BINARY_SEARCH = 1
STRATEGIES_DICT = {LINEAR_SEARCH: "linear", BINARY_SEARCH: "binary"}

SYMMETRY_BREAKING = 0
NO_SYMMETRY_BREAKING = 1
HEURISTICS = 2
SYM_DICT_SAT = { NO_SYMMETRY_BREAKING: "_no_sb", SYMMETRY_BREAKING: "_sb", HEURISTICS: "_no_sb_heu"}
# SAT_SYM_DICT = { NO_SYMMETRY_BREAKING: ""}

# SMTlib
CVC4 = 0
#Z3 = 2
SOLVERS_SMTlib = {CVC4 :"cvc4"}


# MIP
CBC = 0
GLPK = 1
HIGH = 2
GLPK = 1
HIGH = 2
TIME_ORDER = 0
MTZ = 1
DFJ = 2
SYM_DICT_MIP = {NO_SYMMETRY_BREAKING: "",}
STRATEGIES_MIP_DICT = {CBC:"CBC", GLPK:"GLPK"}
SUB_TOURS_MIP_DICT = {TIME_ORDER: "_time_order", MTZ:"_mtz",DFJ: "_DFJ"}

